import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='min-h-screen px-5 py-10 sm:px-8 lg:px-12'>
          <div className='mx-auto w-full max-w-6xl'>{children}</div>
        </main>
      </body>
    </html>
  );
}
